# Autogenerated by devscripts/update-version.py

__version__ = '2023.05.29.042735'

RELEASE_GIT_HEAD = '04abb84e241eb193a8a038debfb8be47b7e2bf25'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
