# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.10.001547'

RELEASE_GIT_HEAD = '888127b56028ef409f0dfdad73597a2418f3ca35'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'highel/yt-dlp'

ORIGIN = 'highel/yt-dlp'

_pkg_version = '2023.12.10.001547'
